server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.88:8848  #nacos服务注册中心
    sentinel:
      transport:
        dashboard: 192.168.184.88:8858   #配置Sentinel dashboard地址
        port: 8719                  #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
      datasource:             #添加nacos作为配置持久化数据源，（也可以将配置持久化到zookeeper,apollo,redis,file中）
        ds1:
          nacos:
            server-addr: 192.168.184.88:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-tpye: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

