server:
  port: 84

spring:
  application:
    name: cloud-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.184.88:8848
    sentinel:
      transport:
        dashboard: 192.168.184.88:8858  #配置sentinel dashboard地址
        port: 8719                      #默认8719端口，假如被占用会自动从8719开始依次扫描，直至找到未占用的端口

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
#激活Sentinel 对Feign的支持
feign:
  sentinel:
    enabled: true
