server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                     #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:                               #路由配置的第一种方法：在yml文件中配置
        - id: payment_routh #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由规则
          uri: lb://cloud-payment-service        #匹配后提供服务的路由规则
          predicates:
           - Path=/payment/get/**           #断言，路由相匹配的进行路由

        - id: payment_routh2 #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由规则
          uri: lb://cloud-payment-service        #匹配后提供服务的路由规则
          predicates:
           - Path=/payment/lb/**            #断言，路由相匹配的进行路由
           - After=2021-09-27T16:12:34.440+08:00[Asia/Shanghai]  #after，在设置的时间之后，配置路由生效
           #- Between=2021-09-27T17:12:34.440+08:00[Asia/Shanghai],2021-09-27T18:12:34.440+08:00[Asia/Shanghai]  #between，在设置的时间之间，配置路由生效
           #- cookie=username,zzyy          #要求携带的cookie中存在username-zzyy的键值对
           #- Header=X-Request-Id, \d+      #请求头要求有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      #集群版
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka