server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: cloud-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: 192.168.115.66
      port: 8500
      discovery:
        #hostname: 192.168.115.66
        service-name: ${spring.application.name}
        #prefer-ip-address: true
        heartbeat:
          enabled: true
